### ISSUE TITLE
[질문] 기능 추가

### ISSUE THREAD

**Issue by broccolism** [thak1411/hyu-lms-helper#2]
@thak1411 
안녕하세요 한양대 컴소 학생입니다.
출결 관련 기능은 아니지만 lms 익스텐션으로 넣을만한 아이디어가 있어서요!
lms 캘린더에 뜨는 일정을 구글 캘린더에 연동해서 lms에 뭔가가 추가되거나 사용자가 추가하면, 연결한 계정의 구글 캘린더 일정에도 함께 추가하는 기능이 있으면 어떨까하는데 제가 개발해서 PR을 넣어도 될까요?
익스텐션 본래 취지와 맞지 않다고 생각하시면 개인적으로 레포 파서 만드려고 합니다.

**Comment by thak1411** [comment]
@broccolism 
오 저는 환영입니다!
dev/morgan 브랜치로 pr 날려주세요 팝업같은거 활용해서 완벽하게 옵션화 되어도 좋을 것 같네요 다만 형태는 어떻든 상관없습니다! 본인의 철학대로 개발하신 뒤 pr 날려주세요!

**Comment by broccolism** [comment]
@thak1411 

알겠습니다 감사합니다!
한창 바쁜 학기에서 그나마 한가한 시기라 속도가 느릴 수 있지만 최대한 빠르게 해볼게요 😇

**Comment by broccolism** [comment]
@thak1411 
안녕하세요 방금 프로젝트 클론을 받았는데요.
제가 생각했던거랑 프로젝트 구조가 너무 달라서 손을 대기가 어려울 것 같아요 😂
사실 밑바닥부터 공부하면 할 수 있을것 같긴 한데, 그렇게 하기엔 졸업 프로젝트랑 이것저것 겹치는 일이 많아서요...ㅎㅎ ㅠ
개인적으로도 필요했던 기능이라 제가 따로 프로젝트 만들고 대신 이 프로젝트에서 motivation을 얻었다고 리드미에 언급해도 될까요?
이슈 남기기 전에 소스코드 한번 봤어야 했는데 성급하게 남긴 것 같아 죄송합니다.

**Comment by thak1411** [comment]
@broccolism 
아닙니다 괜찮습니다.
제가 너무 코드를 대충 짜놓은 것 같습니다 ㅋㅋ 별도의 모듈 관리가 필요 없을 것 같아 너무 막 작업한 것 같습니다..
따로 작업해주셔도 좋을 것 같습니다. 감사합니다.

**Comment by broccolism** [comment]
@thak1411 
이해해주셔서 감사합니다 😇
이 이슈는 제가 닫아놓을게요.
