### ISSUE TITLE
새로고침 할 때에도 페이지 유지

### ISSUE THREAD

**Issue by 1cekrim** [thak1411/hyu-lms-helper#5]
현재 구현에서는 헬퍼를 켜 놓고 새로고침을 하면, 원래 페이지로 이동됨
헬퍼 페이지에서 새로고침을 했을 때, 헬퍼 페이지에 그대로 머물게 하는 것이 좀 더 직관적일 것 같음

**Comment by thak1411** [comment]
컨셉은 좋으나 기술적으로 깔끔하게 가능할지는 모르겠네요 ㅜㅜ url 이 동일한 상황에서 두 페이지를 깔끔하게 컨트롤 할 수 있을까요? 이거저거 들고있어야 할게 많아 질 것 같네요,, 일단 고려해보겠습니다.

**Comment by 1cekrim** [comment]
일단 히스토리 API랑 location.hash 이용해서 구현은 해 놨어요

**Comment by thak1411** [comment]
헉... 팬이에요.. UI/UX가 깔끔하게 나오나요 근데?

**Comment by 1cekrim** [comment]
대시보드 클릭한 다음 HELPER 클릭한 거하고 똑같게 나와요
