### ISSUE TITLE
HELPER를 사용하지 않을 때에도 getCourse가 계속 호출되는 문제

### ISSUE THREAD

**Issue by 1cekrim** [thak1411/hyu-lms-helper#7]
https://github.com/thak1411/hyu-lms-helper/blob/160bccad9f6cae8cf184f20e3b97010da152e448/src/content.js#L326-L330

현재 구현에서는 위와 같이 매번 getCourse를 호출한 이후에 addButtton를 호출함
이런 구조면 HELPER를 사용하지 않을 때에도, 버튼이 추가될 때마다 서버로 리퀘스트를 보내니 비효율적임

버튼을 클릭했을 때만 서버에 리퀘스트를 보내도록 해야 함

https://github.com/thak1411/hyu-lms-helper/blob/160bccad9f6cae8cf184f20e3b97010da152e448/src/content.js#L184-L189

또한 위와 같이 drawTable 함수에서 getCourse가 끝났는지를 유사 재귀를 이용해 체크하고 있음

아마 콜백이 많아져 복잡해지는 것 때문에 위와 같이 구현해 놓으신 것 같은데, async-await으로 잘 짜면 위에 언급한 문제들 해결하면서 코드도 더 깔끔해질 수 있을 듯 합니다

async-await으로 바꾸는 김에 jquery ajax를 fetch로 바꿔도 괜찮을 것 같음 (어차피 한양대 lms는 ie에서 사용 불가능하니 fetch 써도 됨)

**Comment by thak1411** [comment]
꼼수로 작업해놀은 것 때문에 복잡해 보이긴 하네요,, 그리고 버튼을 눌렀을 때 로딩하는건 느릿느릿하게 뜰까봐 미리 받아오게끔 코드를 짰는데 수정을 생각해보긴 해야겠네요

**Comment by 1cekrim** [comment]
사실 리퀘스트 몇 번 더 보낸다고 문제 생길 건 없으니, 지금 구현 그대로 놔둬도 될 것 같기는 합니다
